### ISSUE TITLE
Route "api/rooms" not inside routes/api.php

### ISSUE THREAD

**Issue by blomdahldaniel** [fagray/vuejs2-laravel53-starter#2]
Hi!
This project has been a great tool for me to figure out some things regarding setting up vue with laravel.

However I wonder why  the `Route::get('/api/rooms'....` are inside the `web.php` file  and middleware instead of inside the `api.php` group. Has that to do with the fact that Vue is "inside of laravel" ?

**Comment by fagray** [comment]
Hi  thanks for the feedback. 

This is just a quick setup to get started with vuejs. You are free to tweak it anytime the way you want it. The api/rooms there is just a sample api endpoint. You can transfer it to api.php or whatever file you want to put it.  Or you can also issue a pull request. Thanks

**Comment by fagray** [comment]
I will close this now
