### ISSUE TITLE
direct link to url

### ISSUE THREAD

**Issue by blomdahldaniel** [fagray/vuejs2-laravel53-starter#3]
The application breaks when trying to access a direct url (copied from the vue-router).

So if I click and go to `Foo` => `/foo` and then tries to enter the same url in another tab, the application breaks. 

Some implementation of a middleware or something should fetch the calls or otherwise direct to the vue-router to handle the route..?

**Comment by fagray** [comment]
lol have already read the docs on vue router ? did you know that you cant just copy and paste the url to the browser and do hard page load ? google first your issue before you submit a ticket here, Thanks

**Comment by blomdahldaniel** [comment]
Wow man, beeing rude in open source when all I do is describe my problem. Did you read my comment that says that your repo breaks on my computer doing that? And yes I know vue router and was therefore confused of why it did not work.

Good luck in open source and life with your attitude.

**Comment by fagray** [comment]
Im not being rude here, I'm just trying to educate you. Ofcourse, I do read your comment, but man, you can't do enter a direct url on the browser when the routing mechanism is handled by vuejs and mostly on other SPA frameworks. Please absorb it.
