### ISSUE TITLE
Laravel routes not matching Vue's

### ISSUE THREAD

**Issue by sergiocastrovale** [fagray/vuejs2-laravel53-starter#6]
Hi, thanks a lot for this starter kit. I'm having some issues starting out with Vue 2 integrated into Laravel and this is being very helpful.

I think I found an issue with the project though:

- I go to my 'rooms' list (Vue 2 knows /rooms)
- I hit refresh
- Not found exception (Laravel doesn't know /rooms)

Nothing too critical, just thought you'd like to be aware of it.

**Comment by fagray** [comment]
Hi thanks for using the package.

The routing is handled by the vuejs itself using its own package - vue-router. If you are not building a single page application, then you are free to change your routing mechanism with laravel's built in router. 

Thanks

**Comment by fagray** [comment]
I'll close this now. I'm not considering this as an "issue". Better read the docs carefully if your'e just starting out with vuejs. Thanks

**Comment by fagray** [comment]
Hi thank you for using it.

Vuejs is one of the Single Page Application javascript framework or a SPA
which comprise of master layout wherein the partials are rendered on it.
The routing itself is handled by vue-router not the typical routing scheme
from laravel.

Hope it clears you out. Cheers !

Ray

**Comment by sergiocastrovale** [comment]
I do understand that, but shouldn't things work if I hit refresh on a given page? I'm talking about having a catch-all route on Laravel's end so that any given vue component is rendered properly, like this:

`
Route::get('/{vue?}', function () {
    return view('layouts.app');
})->where('vue', '[\/\w\.-]*');
`

**Comment by fagray** [comment]
Thanks for realizing my mistake. Great suggestion mate !

**Comment by fagray** [comment]
Already made the changes https://github.com/fagray/vuejs2-laravel53-starter/commit/56921331740f4259e7234116ff3e8226f596826f

Thanks mate !
