### ISSUE TITLE
How to compile .Vue files after chnages? 

### ISSUE THREAD

**Issue by misri** [fagray/vuejs2-laravel53-starter#8]
I have chnages the Room.vue file but it is not reflecting in browser.
How to compile these vue files?
are you using gulp to compile vue files?
Please share the command for that 

Thank you

**Comment by fagray** [comment]
Hi thank you for using my package. Please run `npm run dev` or `gulp watch` after changing any .vue files to compile it with webpack. 

Hope it helps ! Thanks
